name: e_commerce_app
description: A simple ecommerce app for flutter using firebase

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #firebase dependency
  firebase_core: "0.5.0+1"
  firebase_auth: "^0.18.1+2"
  cloud_firestore: "^0.14.1+3"

  #Google flutter font
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #material_design_icons_flutter: ^4.0.5755


flutter:

  uses-material-design: true

assets:
  -assets/images/